ame: Production Caller

on:
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/called_workflow.yml
    with:
      environment_name: 'Prod'
      message: 'I am for Production environment'
